- blobdetection.py
**Problem:**
The CellProfiler plugin blobdetection.py throws an error at runtime when the module display window option is selected.
**Suggested solution:**
Remove unsupported named keyword argument "dimensions" from the function call to figure.subplot_imshow. The BlobDetection module now exhibits expected behavior.
**Relevant info:**
Error message:
> Error while processing BlobDetection. 
> subplot_imshow got an unexpected keyword argument 'dimensions'. 
> Do you want to stop processing?
Here's the line detailing keyword argument options from CellProfiler's figure class method 'subplot_imshow'. https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/gui/figure.py
Lline 1223:
~~~~
def subplot_imshow(self, x, y, image, title=None, clear=True, colormap=None,
colorbar=False, …
> blobdetection.py - removed unsupported args from function call to figure.subplot_imshow

- measureradialentropy.py
The MeasureRadialEntropy module was not running as detailed in #25. I identified the problem to be the number of slices an object was divided into was not guaranteed to equal the input parameter. If a slice had no pixels the module would "throw this slice away". An example failing case is if the center of the object is estimated to be outside an object, so far away that none of the labeled object pixels exist to one side. In this case there would be zero pixels for a range of slices.
There are two edits to address this issue. First, the centroid is used in place of the minimum bounding circle center. The minimum bounding circle can be far from from the centroid of the object when the object has "fingers that extend and curve away from the center". Second, when no pixels exist in a slice a …
> change centers and recognize "missing" slices

- mergeobjects.py
- tests/test_mergeobjects.py
Removing objects shouldn't be default behavior and should only occur if the user requests it.
> Make keeping lonely objects the default behavior in MergeObjects

- mergeobjects.py
- tests/test_mergeobjects.py
Previously, the `thick` method for finding borders was adding pixels from the object we were trying to merge, making the algorithm think that itself was always the largest object. Changing the mode to `outer` and changing how an isolated object is detected fixes this.
> Merge objects shouldn't be considering "self" pixels

- predict.py
Create probability maps using an Ilastik pixel classifier. Users must specify the Ilstik executable name, or provide the path to the executable if it is not on the system path. Additionally, users must specify the location of their project (.ilp) file.
Input:
Output:
Probability map segmentation with IdentifyPrimaryObjects:
@chaubold  @stuarteberg @karhohs @bethac07 @0x00b1
> Pixel classification predictions using Ilastik classifier

- .travis.yml
It looks like the `cache` key was missing in the YAML and this caused some parse issues in Travis CI - hope this helps!
> Fix caching section for Travis CI

- activecontourmodel.py
scikit-image's newer (as of 0.14) active contour segmentation methods [morphological geodesic](http://scikit-image.org/docs/dev/api/skimage.segmentation.html#skimage.segmentation.morphological_geodesic_active_contour) and [morphological chan-vese](http://scikit-image.org/docs/dev/api/skimage.segmentation.html#skimage.segmentation.morphological_chan_vese) both require an initial level set geometry and size. Generally the geometry is specific to the segmentation task, but the ideal level set size may differ between images within the same class. By default, these algorithms are naive to what is considered the "foreground" and the "background"; this is determined entirely by the level set specifications. We've found that some of our images given a certain level set segment properly, but other …
> Iterative approach to new scikit-image active contour methods

- classifypixelsunet.py
These are more exhaustive changes to my earlier pull request to fix both 
https://github.com/CellProfiler/CellProfiler-plugins/issues/65
https://github.com/CellProfiler/CellProfiler-plugins/issues/70
It incorporates some of the code snippets suggested by @eric-czech.
* When a model is initialiased, the model size is now scaled to the closest compatible size.
* Any images that are fed to the model are first resized to match the input size of the model (if needed)
* If resizing took place, the predictions are resized to the original input images shape.
> Fixes issues #65 and #70, further changes to more current Keras interface

- .travis.yml
Add [flake8](http://flake8.pycqa.org) tests to find Python syntax errors and undefined names.
__E901,E999,F821,F822,F823__ are the "_showstopper_" flake8 issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree
> Travis CI: Add flake8 to find syntax errors and undefined names

- callbarcodes.py
Fixes the situation where CallBarcodes fails because the barcodes list has a barcode that is empty.
(We encountered this situation where opening the Barcodes.csv in Excel or OpenOffice looked fine but we found that there was an extra empty row `(, , , )` when opened in a text editor.)
> ignore empty barcodes

- runcellpose.py
This plugin provides a wrapper around Cellpose's deep learning segmentation models. Current features:
- Options for most of the basic parameters from the Cellpose API, including mode-switching between detection of nuclei and cells with the inbuilt models.
- Supports using a custom model file, in case you've re-trained the stock models or made your own.
- I've provided the option to run the model on a GPU if it's available. This has additional dependencies and won't work on all systems, so there's also a 'GPU test' button
- Works in 2D or 3D. 3D mode on a GPU requires a lot more VRAM so users may want to resize their images down before trying to run.
- Users can optionally save the probability image alongside the detected objects.
Current interface:
Current figure display (with probability …
> Add RunCellpose plugin

- runstardist.py
Following the theme with RunCellpose, this plugin provides a wrapper around StarDist's deep learning segmentation models. Current features:
- Supports loading of inbuilt StarDist models.
- Supports loading of custom models.
- Will run on a GPU if configured.
- Works in 2D or 3D. The latter requires you to train your own model.
- Can run on brightfield colour images.
- User can capture the probability images.
- Provided settings to tile input images, allowing large images to be processed without running out of memory.
Current interface:
Current figure display (with probability export on):
The dependencies can be a bit of a pain to install, but I think the instructions should be clear enough.
An outstanding issue is that the GPU integration seems to struggle with multiple worker processes. …
> Add RunStarDist plugin

- runcellpose.py
Related to issue #128 and PR #129. Previously RunCellPose provided an error if user chose negative values for the cellprob_threshold. In this PR we allow this threshold to have values between -6 and 6, as explained in the [CellPose docs](https://cellpose.readthedocs.io/en/latest/settings.html#cell-probability-threshold).
> Allow cellprob_threshold to take on values between -6 and 6 in RunCellPose

- runcellpose.py
I have added the `remove_edge_masks` function as described in #168. 
This will allow the user the same functionality that is provided in the `IdentifyPrimaryObjects` and `IdentifySecondaryObjects` modules (e.g. remove objects/cells/nuclei that are have pixels that touch an edge of the image).
> Added "remove_edge_masks" function to RunCellpose module

- active_plugins/cpij/server.py
Required for newer PyImageJ releases (1.4.1) until we have a release with
https://github.com/imagej/pyimagej/commit/a1861b6c1658d6751fa314650b13411f956549ab merged.
Closes #218
> CP-IJ: add workaround for Java names

- setup.py
Disclaimer - this is gross, and I feel gross about it, but it might be the least-worst thing
So if you had the CellProfiler-plugins repo at a pre-reorg commit, you probably had the CellProfiler preference for "where are the plugins" set to the top level, since that's where plugins previously were, and there was not previously a setup.py file. 
Now there IS a setup.py file, and the plugins have moved to the `active_plugins` subfolder, if you still have your plugin-location-preference set to the top level folder, CellProfiler will just point-blank refuse to open, with the error message below. Only moving the setup.py file (or the whole folder) allows you to let CellProfiler open, at which point you could then update the plugin-location-preference, but if you don't know to do that, then you …
> Allow pip installation, but also CellProfiler loading

- setup.py
The latest version of cellpose (cellpose 3) results in an error which is rectified by downgrading to the older versions.
> Cellpose version below 3

- active_plugins/runcellpose.py
Cellpose v2 while reading images converts to float and normalizes the image by setting the first percentile to 0, the 99th percentile to 1, and scaling the image to those values (while clipping the top and the bottom of the distribution).
As this operation is not included when images are loaded in CellProfiler, this step may lead to a mismatch in segmentation when using the Cellpose app vs using the RunCellpose plugin within CellProfiler.
To solve this issue, a setting has been added to allow people to rescale their images before segmenting it through RunCellpose. The default option for this is "yes" and upgrade settings has been set to "no".
> updated runcellpose.py

- active_plugins/filterobjects_stringmatch.py
fix mistake in handling of `METHOD_CONTAINS`, add additional filter methods for keeping string matches
> fix bug, add more settings

- active_plugins/enforceobjectsonetoone.py
> handle input of pre-objects with count 0

- .github/workflows/test.yml
- .github/workflows/test_cellpose.yml
- .github/workflows/test_stardist.yml
Need updated CellProfiler install instructions to get tests running.
As Python3.8 has been deprecated, this may take some troubleshooting so I am disabling automatic testing and will keep issue open in repo noting that it needs to be fixed.
> disable automatic testing

- active_plugins/calculatemoments.py
Fixes #207 and #206.
1. The function `get_object_moment` was not correct, since it failed to use the labels. What it was instead doing was getting a mask of all pixels in the array with the same numerical value, and then calculating the moments on those (which will definitionally be zero), rather than getting the mask for each label in turn. See the old calculatehistogram.py [here](https://github.com/CellProfiler/CellProfiler-plugins/blob/7bfb39005da6717595b9349f320397b4e2ca50ba/unmaintained_plugins/CellProfiler4_autoconverted/calculatehistogram.py#L46)  for an example of how this function used to be implemented.
2. The `fix` in the code was assumed to be`np.fix`, but it's supposed to be `fixup_scipy_ndimage_result as fix` (see elsewhere in the codebase).
Also ran black and flake8 on the …
> [bugfix] adjust calculatemoments code to properly use labels

- active_plugins/boxobjects.py
Cellprofiler plugin with creates bounding box objects from the previously segmented objects
> first draft of BoxObjects
