- measureradialentropy.py
> Add MeasureRadialEntropy

- medialaxis.py
- tests/test_medialaxis.py
Resolves https://github.com/CellProfiler/CellProfiler/issues/3222
> Move MedialAxis to plugins.

- cellprofiler_plugins/setting.py
- measuretrackquality.py
- tests/test_measuretrackquality.py
This should be pretty complete. Has unit tests now.
> MeasureTrackQuality

- mergeobjects.py
- tests/conftest.py
- tests/test_mergeobjects.py
This resolves the issue in the main CellProfiler repo: 
* https://github.com/CellProfiler/CellProfiler/issues/3381
* https://github.com/CellProfiler/CellProfiler/issues/3369
More discussion around this PR: https://github.com/CellProfiler/CellProfiler/pull/3384
> Add MergeObjects module

- mergeobjects.py
Change np to numpy in MergeObjects plugin
> Minor style corrections for MergeObjects

- mergeobjects.py
- tests/test_mergeobjects.py
> Allow option to not remove objects below threshold with no neighbors

- measure_population_context.py
> Update imports for MeasurePopulationContext

- gammacorrection.py
- histogramequalization.py
> Set module_name for GammaCorrection, HistogramEqualization

- README.md
- exporttocellh5.py
- measureimagefocus_README.md
- requirements.txt
> Fix imports for ExportToCellH5

- convertoutlinestoobjects.py
> ConvertOutlinesToObjects

- declump.py
This adds a declumping plugin (a la IdentifyPrimary) for use in 3D. Per @derekthirstrup, he says the results look "just like 2D CellProfiler". Thanks to @thouis for some comments he left behind almost a decade ago to help me figure out why my initial implementation wasn't working as I had expected :grinning:
> 3D Declumping module

- environment.yml
- requirements.txt
- runimagej.py
Run an ImageJ plugin from CellProfiler.
Installation requires [Miniconda](https://conda.io/miniconda.html).
You will also need to clone the [ImageJ server repository](https://github.com/imagej/imagej-server).
**OS X and Linux users:** Edit `environment.yml` to include the `bjornfjohansson` channel and the `wxpython=3.0.2.0` dependency.
Then run the following commands:
```
cd cellprofiler-plugins
conda env create -f environment.yml
source activate cellprofiler-plugins
```
Start the ImageJ server:
```
cd imagej-server
mvn -Pexec
```
Launch CellProfiler:
```
cd cellprofiler-plugins
pythonw -m cellprofiler --plugins-directory .
```
/cc @ctrueden
> [WIP] RunImageJ

- constrainobjects.py
- tests/test_constrainobjects.py
This module will take a set of related reference objects and use it to "trim" the parts of the given objects that protrude past the reference objects.
> ConstrainObjects module

- blobdetection.py
The current export option will merge blobs if they are too close together. This pull request adds an option to export centers, which can be used as seeds for IdentifySecondaryObjects.
> add export option for blob centers

- callbarcodes.py
Add the ability to export barcode scores as an image
> Update barocode calling module

- spectralanalysis.py
> Spectral analysis

- identifylinearobjects.py
> Add IdentifyLinearObjects

- calculatehistogram.py
- calculatemoments.py
- enhancedmeasuretexture.py
- requirements.txt
- transform.py
- transformfilters.py
This includes the May 2018 fix to tranformfilters.py so it is compatible with CP 2.2+
> Include CP Charm in CellProfiler-plugins

- CellProfiler4_AutoConvert/transformfilters.py
Using Python // operator to force integer division for row/col range boundary
>  patch for #111 fixing Haar Wavelet transform error

- callbarcodes.py
>
>
Co-authored-by: Allen Goodman <allen.goodman@icloud.com>
> CP4 updates, fix csv header read issue

- runcellpose.py
Currently the CellPose plugin does not allow for user to specify parameters for `flow_threshold` and `cellprob_threshold` parameters. Defaults are used. This PR adds these two parameters as settings that the user can specify, which are then subsequently used in the `eval()` method of Cellpose's model.
Merging this closes #128
> Add flow_threshold and cellprob_threshold params as cp settings

- runcellpose.py
> Share GPU memory across workers

- runcellpose.py
On Runcellpose, if the model is custom, try to open the model file. If FileNotFound, raise ValidationError in the pipeline for "Failed to load custom file: PATHNAME"
> Added validate_module function to raise ValidationError

- variancetransform.py
Modified the code where it finds the max variance of an image by iterating through a range of window sizes.
> Same functionality, but no pandas

- active_plugins/predict.py
Also, don't make the user have to go in and manually rescale the image, that's unkind
> Fix the predict module on Mac

- active_plugins/callbarcodes.py
Updated documentation for CallBarcodes with more details on channel naming and outputs.
> Update callbarcodes.py docs

- active_plugins/addnoise.py
- documentation/CP-plugins-documentation/supported_plugins.md
Addresses https://github.com/CellProfiler/CellProfiler/issues/2507
Allows user to add Gaussian, Poisson, or Salt and Pepper noise to their images.
> make addnoise plugin

- active_plugins/filterobjects_stringmatch.py
Almost ready but I need one last bit of help. I'm sure I deleted something I wasn't supposed to delete...
I have different behavior in test mode than during analysis mode.
Test mode (works):
Run (does not work):
> add string match to filter objects
